### ISSUE TITLE
Implement quantum execution context

### ISSUE THREAD

**Issue by MichaelBroughton** [tensorflow/quantum#185]
For our slower (cirq_ops) ops where we have the potential of going through to engineSampler in Cirq we might have to drastically change certain execution parameters. For example things like:

1. Reducing from parallel execution to serial execution.
2. Increasing optimization for minimizing circuit depth.
3. Make better use of sweeps.
4. Grouping identical circuits in the batch into the same job.

Need to be defined at the global level. To implement this we should implement a context module in the `python` directory that allows you to set these parameters globally in a thread safe fashion. We can take pretty closely after this: https://github.com/tensorflow/tensorflow/blob/v2.1.0/tensorflow/python/eager/context.py

Implementing this should roughly involve:
1. Implement `quantum_context.py` and tests
2. Implement `engine_util.py` and tests (#186 )
3. Connect `engine_util.py` to `cirq_ops.py` via `quantum_context.py`.
4. Allow users to enable or disable engine compatability mode via `tf.enable_engine_mode` in `util.py`

**Comment by zaqqwerty** [comment]
See the discussion [here](https://github.com/tensorflow/quantum/pull/316#issuecomment-667722886)

**Comment by zaqqwerty** [comment]
For further clarification of my questions under #188 , it seems that the goals listed can all be achieved without adding a global state:
1) I think the choice between parallel and serial execution should be with the cirq object doing the expectation values or sampling, and TFQ should be able to query these objects in a way that is agnostic the choice
2) Minimizing circuit depth is a circuit transformation, so it seems that if this is to be a capability of TFQ then it should be an op ingesting and emitting circuits, rather than something buried in the call to engine.  This seems like something that should be explicit and user-facing because minimizing circuit depth is not a transformation specific to engine.
3) Am I right to assume that "Make better use of sweeps" means something like: identifying when circuits in a batch are identical and calling `run_sweep` with a batch of parameter resolvers instead of calling `run` for each circuit, in order to eliminate the superfluous latency incurred when asking engine to run circuits one-by-one?  If so then this also seems like it should be circuit execution backend specific, and should be something configurable on initialization (that is, these functions would be handled by some TFQ op or Cirq class, rather than being activated by a global state).
4) If identical means the parameters are also the same, then it seems this would benefit any backend, so if we have a good way to do this, we should always do it, rather than only for engine.

**Comment by MichaelBroughton** [comment]
I agree that all the things you have listed can be implemented without global state. Thinking more about this, the ultimate thing we need to have is a convenient way for users to lock down inter and intra op parallelism in order to not drown the engine service. Running on a true chip is a very serial thing and hitting a serial service with huge amounts of parallelism can (and has) led to big problems. TFQ has already DOS'ed engine a few times now.

**Comment by MichaelBroughton** [comment]
This has now been implemented. More properties and configurations to be added.
