### ISSUE TITLE
Standardize layer input tests

### ISSUE THREAD

**Issue by zaqqwerty** [tensorflow/quantum#199]
There is much duplication between layer input checks, would simplify testing if this was abstracted to a separate function

**Comment by zaqqwerty** [comment]
Should also iterate over backends in the layer input tests

**Comment by zaqqwerty** [comment]
Basically, this should change layers to enforce the appropriate data shapes, rather than relying on backend error messages propagating upwards

**Comment by MichaelBroughton** [comment]
Could you try and nail down what the core issue is here ?

Re your points:
1. We probably could have seperate functions that does keras init sanity checks and type checks etc.

2. We don't need to iterate over backends in the layer input tests since the errors and functionality we are testing should not depend on the backend at all.

3. Shape checking is something that belongs at the op level. Shape inference contexts use these when linking tf.functions together. There is no need for us to have duplicate shape error checks, but I agree sometimes discerning whether or not an error is supposed to come from the keras level or the op level can sometimes be tricky.

**Comment by zaqqwerty** [comment]
1) Separate functions make sense here because the boilerplate on the circuit executor layers is not simply error checking, but expansion of various possible inputs to common types and shapes.  Since this code should be identical for all 4 executor layers for their `inputs`, `symbol_names`, and `symbol_values` arguments, it would be better practice to have the code stand-alone.

2) Currently the `sampled_expectation` layer tests have error tests that are specific to the python backend [here](https://github.com/tensorflow/quantum/blob/4d80eeb627fb397f2b9760d8be8295ef5e45c7c2/tensorflow_quantum/python/layers/circuit_executors/sampled_expectation_test.py#L149).  Currently it does depend on the backend, not just the op, for example the "bytes-like" regex.

3) I agree the full shape checking belongs in the op.

**Comment by MichaelBroughton** [comment]
Offline discussion that cleared things up:
1. Discrepancy between different op error strings coming from different backends (C++ python) should be fixed for the sampled expectation layer.
2. While those are being fixed it would also make sense to improve the checks for `inputs`, `symbol_names`, `symbol_values` for execution type layers.

**Comment by MichaelBroughton** [comment]
Has this been resolved now that we have `input_checks.py` in layers ?
