### ISSUE TITLE
Some questions about he MNIST classification example 

### ISSUE THREAD

**Issue by amandalqy** [tensorflow/quantum#203]
Hello! I want to ask some questions about  the MNIST classification example . 
1.“encoding  the data as quantum circuits”:What is the initial quantum state before applying the X gate? |0> or |1 > or  superposition state?And What is the initial quantum state of the readout qubit? 

2. “Build the model circuit ”：  why is the MNIST classification quantum circuit designed as "——X——H——XX——XX...——ZZ——ZZ——H"? Can I use gate YY?

**Comment by MichaelBroughton** [comment]
Here is a link to the paper followed in the tutorial: https://arxiv.org/pdf/1802.06002.pdf (also linked in the tutorial), they go over all of the model specifics in detail. To answer your questions:

1. The initial state of all of the qubits in a circuit are  |0>. In Cirq this is an implicit assumption so anytime you enact a sequence of gates you can always assume a qubit started in the |0> state before any of the gates are enacted. That is why you can see in the example in order to get the designated readout qubit into the |1> state we apply an X gate to it.

2. In the paper the authors use XX and ZZ gates between qubits, but it is entirely reasonable to try other parameterized two qubit gate combinations.

**Comment by amandalqy** [comment]
Thank you !  It helps me a lot!

**Comment by MichaelBroughton** [comment]
No problem
