### ISSUE TITLE
Best material to follow and learn?

### ISSUE THREAD

**Issue by dsantiago** [tensorflow/quantum#359]
Hi guys i am reading the repo and the intro notebooks but  i do not have the baseline knowledge for Quantum Computing... Do you guys have any study flow to keep up with the rest of the contributors here?

Thanks in advance!

**Comment by MichaelBroughton** [comment]
Of course! In my humble opinion, In order to be able to follow along and understand TFQ, I would recommend doing the following:

1. Do some reading. My first QC book was: http://mmrc.amss.cas.cn/tlb/201702/W020170224608149125645.pdf This was a great starter book because the math didn't overwhelm me and things were easy to digest if I read slowly and carefully (doing the exercises along the way helped build confidence too). After that I read: http://mmrc.amss.cas.cn/tlb/201702/W020170224608149940643.pdf (Which is like the CLRS for QC), this book was much more of a hurdle to get over and took many many months to read. If you feel relatively confident with the math already there's lots of good papers that explain where we currently are in the field of QC ( like this one: https://arxiv.org/abs/1801.00862 ).

2. Give Cirq a whirl. https://github.com/quantumlib/Cirq . In order to use TFQ at all, you will have to know the basics of Cirq (Which does require step 1 to be completed somewhat).

3. Try out the TFQ tutorials and following along with the math and paper links we provide: https://www.tensorflow.org/quantum , Understanding how the QC primitives operate alongside TF ( understanding the shape transforms will be a big plus here).

Steps 1 and 2 can sort of be done in parallel if you're careful :)

Hopefully that's enough of a starting point. Going to close this for now, since this isn't really an issue with the code and might be a question more appropriate for a place like StackOverflow.

**Comment by dsantiago** [comment]
Thank you so much Michael for the intuition on where to start...  This topic may help other newbies, maybe you can label it with "question".
