### ISSUE TITLE
Data reuploading using PQC layer(s)

### ISSUE THREAD

**Issue by luuk-visser** [tensorflow/quantum#468]
I'm trying extend my parametrized quantum circuit to use data re-uploading, as proposed by [Pérez-Salinas et  al.](https://arxiv.org/pdf/1907.02085.pdf)

Currently, my model exists of a single Input layer and a single PQC layer. I would like to split my single PQC layer into multiple layers such that the data uploading layers can be inserted in between the PQC layers. As tfq.layers.PQC requires a measurement, I'm required to change the PQC layers to something else. 

However, the alternatives (State and maybe AddCircuit) do not accept a differentiator kwarg, and as I'm experimenting with different types of layers I would like to refrain from implementing a custom gradient for each of these. What are currently my best options to implement this?

Thanks in advance!

**Comment by ghellstern** [comment]
Hi Luuk,

I struggled with the same Problem; have a look at issue

#267 PQC in the middle of network, contd.

There a soltution is presented which helps to implement the data reuploading approach... If you are interested to discuss further just tell me.

All the best 
Gerhard

**Comment by luuk-visser** [comment]
Hi Gerhard, thank you for your suggestion!

The problem I'm currently having is that I'm trying to insert Input layers (to input encoding circuits) in between parametrized quantum layers. Based on the solution to #267, I created a small example of what I'm trying to achieve:

```python
import cirq
import sympy
import numpy as np
import tensorflow as tf
import tensorflow_quantum as tfq

def param_layer(qubit, curr_depth):
    theta = sympy.Symbol(str(curr_depth))
    yield cirq.rz(theta).on(qubit)
        
class customPQC(tf.keras.layers.Layer):
    def __init__(self, qubit, n_layers=2):
        super().__init__(customPQC)
        self.n_layers = n_layers
        self.qubit = qubit
        self.symbols = [sympy.Symbol(str(i)) for i in range(n_layers)]
        
    def build(self, input_shape):
        self.managed_weights = self.add_weight(
            shape=(1,len(self.symbols)),
            initializer=tf.keras.initializers.RandomUniform(0, 2 * np.pi))
        
    def call(self, encoding_circuit):
        circuit_tensor = tfq.convert_to_tensor(cirq.Circuit())
        for curr_depth in range(self.n_layers):
            circuit_tensor = tfq.layers.AddCircuit()(
                circuit_tensor, 
                append=encoding_circuit
            )
            circuit_tensor = tfq.layers.AddCircuit()(
                circuit_tensor, 
                append=param_layer(self.qubits, curr_depth)
            )
            
        ops = cirq.Z(self.qubit)
        return tfq.layers.Expectation()(
            circuit,
            operators=ops,
            symbol_names=self.symbols,
            symbol_values=self.managed_weights
        )


qubit = cirq.GridQubit(0,0)

input_layer = tf.keras.Input(shape=(), dtype=tf.string)
output_layer = customPQC(qubit)(input_layer)
model = tf.keras.Model(inputs=input_layer, outputs=output_layer)
```

However, this gives me the following error:
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-15de7900ff44> in <module>
     45 
     46 input_layer = tf.keras.Input(shape=(), dtype=tf.string)
---> 47 output_layer = customPQC(qubit)(input_layer)
     48 model = tf.keras.Model(inputs=input_layer, outputs=output_layer)

~/venv/lib64/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, *args, **kwargs)
    924     if _in_functional_construction_mode(self, inputs, args, kwargs, input_list):
    925       return self._functional_construction_call(inputs, args, kwargs,
--> 926                                                 input_list)
    927 
    928     # Maintains info about the `Layer.call` stack.

~/venv/lib64/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py in _functional_construction_call(self, inputs, args, kwargs, input_list)
   1115           try:
   1116             with ops.enable_auto_cast_variables(self._compute_dtype_object):
-> 1117               outputs = call_fn(cast_inputs, *args, **kwargs)
   1118 
   1119           except errors.OperatorNotAllowedInGraphError as e:

~/venv/lib64/python3.6/site-packages/tensorflow/python/autograph/impl/api.py in wrapper(*args, **kwargs)
    256       except Exception as e:  # pylint:disable=broad-except
    257         if hasattr(e, 'ag_error_metadata'):
--> 258           raise e.ag_error_metadata.to_exception(e)
    259         else:
    260           raise

TypeError: in user code:

    <ipython-input-3-15de7900ff44>:26 call  *
        circuit_tensor = tfq.layers.AddCircuit()(
    /home/s1707264/venv/lib64/python3.6/site-packages/tensorflow_quantum/python/layers/circuit_construction/elementary.py:128 call  *
        return tfq_utility_ops.tfq_append_circuit(inputs, append)
    <string>:65 tfq_append_circuit  **
        
    /home/s1707264/venv/lib64/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:493 _apply_op_helper
        (prefix, dtypes.as_dtype(input_arg.type).name))

    TypeError: Input 'programs' of 'TfqAppendCircuit' Op has type float32 that does not match expected type of string.

```

Even if this solution were to work, it rebuilds the entire circuit for every single call made, which seems to me like unnecessary overhead. Any suggestions to fix and/or improve upon this?

**Comment by ghellstern** [comment]
Hi Luuk, 
I'm a little bit confused about your code - putting everything together in one class is maybe possible but at least for me too complicated :-(  
See below the code which implements data-reuploading in a 1-dim toy example. Extending it to more qubits and higher dimensional data is straightforward. The only trick needed is the splitting layer. I worked out an example which uses data reuploading for MNIST-data and up to 15 Qubits and it really works ;-) By adding clasical layers before and after the quantum network you can further condense and transform the input data and the measurement results which is quite useful imho.... 
Good luck ! Gerhard  


import tensorflow as tf
import tensorflow_quantum as tfq
import cirq
import sympy
import numpy as np
import matplotlib.pyplot as plt

class SplitBackpropQ(tf.keras.layers.Layer):

    def __init__(self, upstream_symbols, managed_symbols, managed_init_vals,
                 operators):
        """Create a layer that splits backprop between several variables.


        Args:
            upstream_symbols: Python iterable of symbols to bakcprop
                through this layer.
            managed_symbols: Python iterable of symbols to backprop
                into variables managed by this layer.
            managed_init_vals: Python iterable of initial values
                for managed_symbols.
            operators: Python iterable of operators to use for expectation.

        """
        super().__init__(SplitBackpropQ)
        self.all_symbols = upstream_symbols + managed_symbols
        self.upstream_symbols = upstream_symbols
        self.managed_symbols = managed_symbols
        self.managed_init = managed_init_vals
        self.ops = operators

    def build(self, input_shape):
        self.managed_weights = self.add_weight(
            shape=(1, len(self.managed_symbols)),
            initializer=tf.constant_initializer(self.managed_init))

    def call(self, inputs):
        # inputs are: circuit tensor, upstream values
        upstream_shape = tf.gather(tf.shape(inputs[0]), 0)
        tiled_up_weights = tf.tile(self.managed_weights, [upstream_shape, 1])
        joined_params = tf.concat([inputs[1], tiled_up_weights], 1)
        return tfq.layers.Expectation()(inputs[0],
                                        operators=ops,
                                        symbol_names=self.all_symbols,
                                        symbol_values=joined_params)
#Create One-Dimensional-Data for Classification
np.random.seed(seed=123)
n = 900
data = np.random.rand(n, 1)
labels = []
for p in range(0, n):
    if data[p] <= 0.5:
        label = [1, 0]
    else:
        label = [0, 1]
    labels.append(label)
labels = np.array(labels, dtype=np.int32)

bit = cirq.GridQubit(0, 0)
symbols = sympy.symbols('alpha, beta, gamma, eta')
ops = [cirq.Z(bit)]
circuit = cirq.Circuit(
#   Data is encoded via first Y-rotation:
    cirq.Y(bit)**symbols[0],
    cirq.Y(bit)**symbols[1],
    cirq.Z(bit)**symbols[2],
    cirq.Y(bit)**symbols[3],
##  Addding the data-encoding again corresponds to data-reuploading: 
    cirq.Y(bit)**symbols[0],
)

data_input = tf.keras.Input(shape=(1,), dtype=tf.dtypes.float32)

#Use a classical NN to transform the data
encod_1 = tf.keras.layers.Dense(10, activation=tf.keras.activations.relu)(data_input)
encod_2 = tf.keras.layers.Dense(1, activation=tf.keras.activations.sigmoid)(encod_1)

# This is needed because of Note here:
# https://www.tensorflow.org/quantum/api_docs/python/tfq/layers/Expectation
unused = tf.keras.Input(shape=(), dtype=tf.dtypes.string)

expectation = SplitBackpropQ(['alpha'], ['beta', 'gamma', 'eta'], [np.pi / 2, np.pi/2, np.pi/2 ],
                             ops)([unused, encod_2])

classifier = tf.keras.layers.Dense(2, activation=tf.keras.activations.softmax)
classifier_output = classifier(expectation)

model = tf.keras.Model(inputs=[unused, data_input], outputs=classifier_output)

tf.keras.utils.plot_model(model, show_shapes=True, dpi=70)

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
              loss=tf.keras.losses.mean_squared_error)
#model.compile(optimizer='Adam', loss='mse')

history=model.fit([tfq.convert_to_tensor([circuit for _ in range(n)]), data],
          labels, batch_size=10,
          epochs=100)

# Now we can see 37 parameters. Two of which belong to "SplitBackpropQ"
# since we told it above on L81 that we want it to manage ["beta", "gamma"]
print(model.trainable_variables)

plt.plot(history.epoch,  history.history['loss'])

**Comment by luuk-visser** [comment]
Hi Gerhard, after trying to get this to work for a long time I just realized I might as well use instances of the entire circuit (including parametrized layers) as input for the model. My problem was the fact that I wanted to represent only the data-encoding part of the circuit as input to the model, which I guess would be more elegant but I'm already happy to finally have my code running now. Thanks for your help!

**Comment by MattWard97** [comment]
> Hi Gerhard, after trying to get this to work for a long time I just realized I might as well use instances of the entire circuit (including parametrized layers) as input for the model. My problem was the fact that I wanted to represent only the data-encoding part of the circuit as input to the model, which I guess would be more elegant but I'm already happy to finally have my code running now. Thanks for your help!

@luuk-visser Doesn't The tensorflow-quantum PQC layer documentation say that you can not have free parameters in the input to the PQC layer? _"In order to extract information from our circuit, we must apply measurement operators. For now we choose to make a Z measurement. In order to observe an output, we must also feed our model quantum data (NOTE: quantum data means quantum circuits with no free parameters)."_ So you are saying your input to the PQC layer DOES have free sympy parameters / weights? Did this work for you? Thanks

**Comment by lockwo** [comment]
My goto method for data reuploading is to use some free parameters (for reuploading) and some non-free by using the ControlledPQC layer. You can see examples of how to do this here: https://www.tensorflow.org/quantum/tutorials/quantum_reinforcement_learning, https://github.com/lockwo/quantum_computation/blob/master/TFQ/data_reupload/uat.py, https://github.com/lockwo/quantum_computation/blob/master/TFQ/data_reupload/reup.py.

Regarding your specific question, yes the input to the PQC should be unbound parameter free.

**Comment by anikde** [comment]
I am facing a similar problem, my parameterized circuit is a 3-qubit model
![Uploading image.png…](Parameterized circuit)

 in which I am using a encoder circuit 
![Uploading imageedit_4_6561136313.jpg…](Encoder Circuit). The trainable parameters are suffixed with T and input parameters are prefixed with I. 
The encoder circuit can encode data dimension of (12,).
So, I know the input to the model should be of size (12, ). But since my circuit is of 3-qubit in to make changes in to the call function which not able to understand, particularly ```tf.einsum```. 
The code below is custom_layer class from [tensorflow_quantum_reinforcement_learning_notebook](https://www.tensorflow.org/quantum/tutorials/quantum_reinforcement_learning), however I changed the model circuit as per my requirement. 

```
class ReUploadingPQC(tf.keras.layers.Layer):
    """
    Performs the transformation (s_1, ..., s_d) -> (theta_1, ..., theta_N, lmbd[1][1]s_1, ..., lmbd[1][M]s_1,
        ......., lmbd[d][1]s_d, ..., lmbd[d][M]s_d) for d=input_dim, N=theta_dim and M=n_layers.
    An activation function from tf.keras.activations, specified by `activation` ('linear' by default) is
        then applied to all lmbd[i][j]s_i.
    All angles are finally permuted to follow the alphabetical order of their symbol names, as processed
        by the ControlledPQC.   
 """
 def __init__(self, qubits, n_layers, observables, activation="linear", name="re-uploading_PQC"):
        super(ReUploadingPQC, self).__init__(name=name)
        self.n_layers = n_layers
        self.n_qubits = len(qubits)
        self.observables = observables

        circuit, theta_symbols, input_symbols = generate_circuit(qubits, n_layers)
        self.circuit = circuit

        theta_init = tf.random_uniform_initializer(minval=0.0, maxval=np.pi)
        self.theta = tf.Variable(
            initial_value=theta_init(shape=(1, len(theta_symbols)), dtype="float32"),
            trainable=True, name="thetas"
        )

        lmbd_init = tf.ones(shape=(self.n_qubits * self.n_layers,))
        self.lmbd = tf.Variable(
            initial_value=lmbd_init, dtype="float32", trainable=True, name="lambdas"
        )

        # Define explicit symbol order.
        symbols = [str(symb) for symb in theta_symbols + input_symbols]
        self.indices = tf.constant([symbols.index(a) for a in sorted(symbols)])

        self.activation = activation
        self.empty_circuit = tfq.convert_to_tensor([cirq.Circuit()])
        self.computation_layer = tfq.layers.ControlledPQC(self.circuit, self.observables)        

    def call(self, inputs):
        # inputs[0] = encoding data for the state.
        batch_dim = tf.gather(tf.shape(inputs[0]), 0)
        tiled_up_circuits = tf.repeat(self.empty_circuit, repeats=batch_dim)
        tiled_up_thetas = tf.tile(self.theta, multiples=[batch_dim, 1])
        tiled_up_inputs = tf.tile(inputs[0], multiples=[1, self.n_layers])
        scaled_inputs = tf.einsum("i,ji->ji", self.lmbd, tiled_up_inputs)
        squashed_inputs = tf.keras.layers.Activation(self.activation)(scaled_inputs)

        joined_vars = tf.concat([tiled_up_thetas, squashed_inputs], axis=1)
        joined_vars = tf.gather(joined_vars, self.indices, axis=1)

        return self.computation_layer([tiled_up_circuits, joined_vars])
```
        Then when I try to create model with following lines of code 
  ```
def generate_model_policy(qubits, n_layers, n_actions, beta, observables):
    """Generates a Keras model for a data re-uploading PQC policy."""

    input_tensor = tf.keras.Input(shape=(12, ), dtype=tf.dtypes.float32, name='input')
    re_uploading_pqc = ReUploadingPQC(qubits, n_layers, observables)([input_tensor])
    process = tf.keras.Sequential([
        Alternating(n_actions),
        tf.keras.layers.Lambda(lambda x: x * beta),
        tf.keras.layers.Dense(3, activation="softmax"),
    ], name="observables-policy")
    policy = process(re_uploading_pqc)
    model = tf.keras.Model(inputs=[input_tensor], outputs=policy)

    return model

model = generate_model_policy(qubits, n_layers, n_actions, 1.0, observables)```
The error is 
```
Exception encountered when calling layer "re-uploading_PQC" (type ReUploadingPQC).

in user code:

    File "/tmp/ipykernel_1109761/1735579080.py", line 45, in call  *
        scaled_inputs = tf.einsum("i,ji->ji", self.lmbd, tiled_up_inputs)

    ValueError: Dimensions must be equal, but are 3 and 12 for '{{node re-uploading_PQC/einsum/Einsum}} = Einsum[N=2, T=DT_FLOAT, equation="i,ji->ji"](re-uploading_PQC/einsum/Einsum/ReadVariableOp, re-uploading_PQC/Tile_1)' with input shapes: [3], [?,12].


Call arguments received:
  • inputs=['tf.Tensor(shape=(None, 12), dtype=float32)'
```
I didn't understand how tf.einsum works here.

**Comment by lockwo** [comment]
Einsum should be fine here, as long as the dimensions are correct (if you want to understand einsum read: https://rockt.github.io/2018/04/30/einsum). It appears as though the issue is with shapes. Lambda assumes structure that isn't true. If you look in the tutorial, there are 1 param per 1 qubit for the lambda parameters. However, you want 3 lambda parameters per qubit because the ansatz is different. So the lambda is creating the wrong number of parameters (which then errors when you feed it into the model creation)

**Comment by anikde** [comment]
Thanks, I didn't count the number of parameters in the ```lmbd_init``` variable. 
```
        n_qubits = 3
        n_layers = 1
```
```
        lmbd_init = tf.ones(shape=(self.n_qubits * 4 * self.n_layers,))
        self.lmbd = tf.Variable(
            initial_value=lmbd_init, dtype="float32", trainable=True, name="lambdas"
        )
```
I have changed the shape of ```lmda_init``` to (12, ), and now the the code work. This would probably help me complete my masters, so thanks a lot.
