### ISSUE TITLE
New noise tutorial

### ISSUE THREAD

**Issue by zaqqwerty** [tensorflow/quantum#573]
The [original noise tutorial](https://github.com/tensorflow/quantum/pull/454) was written prior to the introduction of noisy ops into TFQ.  Now that we have these, a new tutorial is appropriate.  One idea is to base it on a well understood paper.  In the comments below, feel free to propose papers or other ideas on what this tutorial should look like.

**Comment by lockwo** [comment]
I'm not sure if any of these are really "seminal" or well established enough, but maybe they can help generate some ideas: 
- [Machine Learning of Noise-Resilient Quantum Circuits](https://journals.aps.org/prxquantum/pdf/10.1103/PRXQuantum.2.010324)
- [Machine learning of high dimensional data on a noisy quantum processor](https://arxiv.org/pdf/2101.09581.pdf)
- [Optimizing parametrized quantum circuits via noise-induced breaking of symmetries](https://arxiv.org/pdf/2011.08763v1.pdf)
- [Noise robustness and experimental demonstration of a quantum generative adversarial network for continuous distributions](https://arxiv.org/pdf/2006.01976.pdf)

Also, since every hardware experiment is noisy, maybe recreating experimental papers (w/ noise) is an idea:
- [Generation of High-Resolution Handwritten Digits with an Ion-Trap Quantum Computer](https://arxiv.org/pdf/2012.03924.pdf), [Experimental Quantum Generative Adversarial Networks for Image Generation](https://arxiv.org/pdf/2010.06201.pdf)
- [Hartree-Fock on a superconducting qubit quantum computer](https://arxiv.org/pdf/2004.04174.pdf)
- [Analyzing the Performance of Variational Quantum Factoring on a Superconducting Quantum Processor](https://arxiv.org/pdf/2012.07825.pdf)

**Comment by MichaelBroughton** [comment]
Put a candidate tutorial up that makes use of our `tfq.datasets` module. I read through the list of papers here and a lot of them seemed pretty tricky to implement alongside an introduction to noise basics in TFQ so I opted to shorten up the recreating a paper from the wild part so that there was more room for this noise introduction. What do people think of #582 ?
