### ISSUE TITLE
Upgrade to sympy v 1.7

### ISSUE THREAD

**Issue by simonwa7** [tensorflow/quantum#589]
Hi all!

I was wondering if there were any plans to upgrade tfq to be compatible with the newer versions of sympy? I am currently working on a project that requires `sympy>=1.7`, but I see there is a strict requirement on `sympy==1.5` within the `requirements.txt`. I am hoping to work with tensorflow-quantum, but I am currently blocked by this compatibility issue. 

Happy to help in any way that I can!

Thanks!

**Comment by MichaelBroughton** [comment]
Hi @simonwa7 thanks for raising the issue.

This is absolutely something we can work on and probably get done pretty quick.

I'll look into this later this week.

@jaeyoo I have this faint memory of us choosing sympy 1.5 because it behaved better when serializing (particularly with rounding), do you remember if there were any other reasons we locked onto 1.5 ?

**Comment by jaeyoo** [comment]
Hmm i don't remember it. l am pretty open to upgrade to Sympy 1.7.

**Comment by simonwa7** [comment]
Thank you @MichaelBroughton and @jaeyoo :) This is really helpful!

**Comment by MichaelBroughton** [comment]
This should now appear in the latest `tfq-nightly` install
