### ISSUE TITLE
when using tensorflow 2.4. 1 and tfq 0.3.1, it raises _tfq_simulate_ops.so not found  

### ISSUE THREAD

**Issue by ll971** [tensorflow/quantum#640]
import tensorflow as tf
import tensorflow_quantum as tfq

import cirq
import sympy
import numpy as np

error in  2nd line:

tensorflow.python.framework.errors_impl.NotFoundError: D:\Anaconda3\envs\w\Lib\site-packages\tensorflow_quantum\core\ops\_tfq_simulate_ops.so not found

**Comment by lockwo** [comment]
TFQ 0.3.1 has the following requirements:
cirq==0.8.0
sympy==1.4
nbconvert==5.6.1
nbformat==4.4.0
pylint==2.4.4
yapf==0.28.0
tensorflow==2.1.0
pathos==0.2.5
google-api-python-client==1.8.0

It is probably breaking because tensorflow 2.4.1 is not what it requires.

**Comment by ll971** [comment]
Thanks for your reply, I want to run a tfq program on RTX 3060. How can I make it?  RTX 3060 only suport for the CUDA 11.1, 
Does tensorflow-gpu 2.1.0 can works with CUDA 11.1?


> TFQ 0.3.1 has the following requirements: cirq==0.8.0 sympy==1.4 nbconvert==5.6.1 nbformat==4.4.0 pylint==2.4.4 yapf==0.28.0 tensorflow==2.1.0 pathos==0.2.5 google-api-python-client==1.8.0
> 
> It is probably breaking because tensorflow 2.4.1 is not what it requires.

**Comment by lockwo** [comment]
I don't think (someone can correct me if I'm mistaken) that TFQ 0.3.1 can run on GPU. Since qsim didn't add GPU support till 0.10 (which happened Jul 29 2021, more than a month after the release of TFQ 0.5.1, maybe the nightly build has something I haven't really been keeping up with it).  

Tensorflow 2.1.0 works with CUDA 10.1. CUDA 11.1 wasn't added until Tensorflow 2.5 (according to this table: https://www.tensorflow.org/install/source#gpu)
