### ISSUE TITLE
Would it be possible to relax the requirements?

### ISSUE THREAD

**Issue by BastianZim** [tensorflow/quantum#648]
Hi,

this issue is primarily along the lines of https://github.com/tensorflow/tensorflow/commit/a90383a867a2337600c775d67842f308da9d118b. 
I was wondering if the tight pins in `requirements.txt` are primarily due to functionality or solvability? Reason is, that I'm thinking about adding this package to conda-forge but the restrictions currently make this difficult.
It seems like things like the numpy pin are primarily to make solving easier but I just wanted to double check if this is correct?
Thanks!

**Comment by MichaelBroughton** [comment]
Hi @BastianZim thanks for opening the issue. There are a few reasons why we pin specific versions (most being for functionality)

1. We pin `TensorFlow==2.5.1` because all of the C++ code we have inside of TFQuantum (and all other custom C++ tensorflow repos for that matter) rely on ABI stability. If you were to install the latest TFQ and install any version of TensorFlow other than 2.5.1 you might see symbol table lookup issues like this one: https://github.com/tensorflow/quantum/issues/180 .
2. The proto version requirements we inherit from TF. I think these could be relaxed. Maybe try opening a PR to experiment ?
3. The numpy pin is one we also inherit from TF.

Also note we use `requirements.txt` for setting up a development environment, but the requirements we impose on the user can be found in `setup.py`.

Most of these requirements trickle down to us from TF and the known toolchain + flags that are used to compile it. On conda I believe that the process isn't identical and it could wind up that you might need to compile TFQ using whatever flags match the ones on conda. Looking here: https://anaconda.org/conda-forge/tensorflow/files?version it looks like conda doesn't host TF 2.5.1, so that may already be a non-starter, until we can get an upgrade on the version of TF we depend on here in TFQ.

**Comment by BastianZim** [comment]
Hi @MichaelBroughton thanks for the reply. Let me answer in a list as well, just to make it easier.

1. Ok makes sense. I wasn't sure if Tensorflow follows SemVer where the patches shouldn't matter but it you require an exact pin then of course it's different.

**Comment by BastianZim** [comment]
I would also have one question regarding the compilation: Proto etc. is generally, in my experience, required during compilation and then when running the package, but from what I can see the only thing required [here](https://github.com/tensorflow/quantum/blob/master/docs/install.md) (Besides the compiler toolchain) is Tensorflow. Is that correct?

**Comment by MichaelBroughton** [comment]
We use the version of [protoc provided by TensorFlow](https://github.com/tensorflow/tensorflow/blob/8f761b623768c5ed59a502d7eff35cc0c3bccb16/tensorflow/workspace2.bzl#L447) in our project (via bazel dependencies) when developing code:
1. We use this protobuf for Codegen + Compilation in C++
2. We also use it for Codegen in python
When actually running code all we require is that you use a version of [this](https://pypi.org/project/protobuf/) that happens to also work with the current version of protoc used in TensorFlow. Right now protoc 3.9.2 is used, but for the ease of our users we can allow the pip install to slide all the way up to [3.17.3](https://github.com/tensorflow/quantum/blob/8cda8f035cdec42fca0c56529735c0911394b979/requirements.txt#L16)

This is a problem TensorFlow also has and is working on fixing [here](https://github.com/tensorflow/tensorflow/issues/53234)

**Comment by lockwo** [comment]
Any updates on this issue or can it be closed?

**Comment by mihaimaruseac** [comment]
TF fixed the protobuf issue in https://github.com/tensorflow/tensorflow/commit/84f40925e929d05e72ab9234e53c729224e3af38
