### ISSUE TITLE
Remove set-output in Github Action CI.

### ISSUE THREAD

**Issue by jaeyoo** [tensorflow/quantum#750]
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by jaeyoo** [comment]
https://github.com/actions/setup-python maybe do we need to bump up the vesion? (from v1 to v2?)

**Comment by mhucka** [comment]
@jaeyoo I'm working on updating the GitHub Actions workflows and will be updating the versions. I'm going ahead and assigning myself to this issue, but if you want to do something with it or have some in-progress work, please let me know. (I realize that's unlikely given how old this issue is; still, it's polite to ask …)

**Comment by mhucka** [comment]
It looks like none of the workflows use this construct anymore. This issue was probably completed some time in the past. Closing.
